#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Asgl.Droid.RatingView.Library.Resource", IsApplication=false)]

namespace Asgl.Droid.RatingView.Library
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int rating = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int readOnly = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int requiresCorrection = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int scale = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public static int colourBad = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int colourDisabled = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int colourGood = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int colourImportant = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int colourNotImportant = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_action_bad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_action_good = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_action_important = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_action_not_important = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public static int not_applicable = 2131099655;
			
			// aapt resource value: 0x7f060002
			public static int rating0 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int rating1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int rating2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int rating3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int rating4 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public static int req_correction = 2131099656;
			
			// aapt resource value: 0x7f060001
			public static int rvRow = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int rvTable = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int angus_rating_view = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RatingView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int RatingView_rating = 1;
			
			// aapt resource value: 2
			public static int RatingView_readOnly = 2;
			
			// aapt resource value: 3
			public static int RatingView_requiresCorrection = 3;
			
			// aapt resource value: 0
			public static int RatingView_scale = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
